#!/bin/bash

# git config file path
git_config=~/.gitconfig 

# grab the user's git username
username=$(git config --file $git_config --get user.name)

# grab the commit hash of the most recent commit that isn't theirs
commit_hash=$(git log --format='%H %an' | grep -v $username | cut -d ' ' -f1 | head -1)

# begin rebase in cwd based on that commit hash
git rebase -i $commit_hash
